### ISSUE TITLE
Wrong definition of LuaL.unref

### ISSUE THREAD

**Issue by VLanvin** [pdonadeo/ocaml-lua#11]
At line 262 of lua_aux_lib.ml (and at line 327 of the corresponding .mli), the function unref is set to `luaL_ref__stub` when it should be set to `luaL_unref__stub`, potentially causing errors. The full line should be:

`external unref : state -> int -> int -> unit = "luaL_unref__stub"`

**Comment by pdonadeo** [comment]
@VLanvin sorry for the delay, I'm going to check tomorrow.
