### ISSUE TITLE
Undefined error LUA_ERRFILE

### ISSUE THREAD

**Issue by VLanvin** [pdonadeo/ocaml-lua#12]
At line 10 of lua_api_lib.ml and in the corresponding .mli, the value LUA_ERRFILE is missing from the variant thread_status, which causes a failure in the function `thread_status_of_int` (line 48). 
This error is defined at line 32 of lauxlib.h:

`#define LUA_ERRFILE     (LUA_ERRERR+1)`

Note: this error can happen when trying to call `dofile` on a non-existing file for example.

**Comment by pdonadeo** [comment]
@VLanvin sorry for the delay, I'm going to check tomorrow.
