### ISSUE TITLE
Is it safe to allow 4.03.0 and up?

### ISSUE THREAD

**Issue by SGrondin** [pdonadeo/ocaml-lua#13]
See https://github.com/pdonadeo/ocaml-lua/blob/1c1672b5a65ba849296d8fa517c30bc7d17eeb8d/opam/ocaml-lua.1.5/opam#L42

If it isn't safe, what work needs to be done? I'd be glad to contribute.

**Comment by SGrondin** [comment]
I removed that restriction in my fork and it seems to be working great in 4.04.1. I've read the Changelogs for 4.03.0, 4.04.0 and 4.04.1, I didn't see anything that would conflict with `ocaml-lua` (I've read the stubs code many times).

**Comment by pdonadeo** [comment]
Actually... I never compiled with nothing newer than 4.02.3. This week end I'm going to check with new compilers.

**Comment by pdonadeo** [comment]
After a few months... I just checked the package against OCaml up to 4.05.0, created a new minor release (1.6) and submitted to opam-repository.

The problem with this project is that it's not up to date with Lua 5.3 but sadly I have no time to make a major update 😞

**Comment by SGrondin** [comment]
Don't worry too much about it, Lua 5.1 and Lua (5.2, 5.3, then 5.4, etc) have effectively become 2 distinct languages. Lua 5.1 will be used in embedded for a long time to come because it's a simple and stable target. The ever-evolving Lua language (now on 5.3) has been adding too many features for some people. I wouldn't have used ocaml-lua if it had supported 5.3 but not 5.1.

**Comment by pdonadeo** [comment]
I admit I lost contact with the Lua community so I didn't know about this "kind of fork".

In any case I want, at least, to rework the project, to revamp the build system and make the repository compatible with OCaml 4.06.0.
