### ISSUE TITLE
Wrong use of CAMLlocal

### ISSUE THREAD

**Issue by damiendoligez** [pdonadeo/ocaml-lua#8]
At line 236 of `src/stub.c` (first line of `writer_function`) you use `CAMLlocal` outside the scope of `CAMLparam`. This is a mistake and potentially a crashing bug. OCaml 4.04.0 and later will prevent this mistake by triggering a C compiler error in such cases.

In this case, you should replace the line with:
```
  value writer_status_value, buffer;
```
because neither value stays alive through an allocation.

**Comment by pdonadeo** [comment]
@damiendoligez thanks for opening this issue and thanks for the fix. I'm going to fix this tomorrow.

**Comment by pdonadeo** [comment]
Closed with pdonadeo/ocaml-lua@8a41b3f882cc32b7af85baedfb82cee60aca3ed7

I'm going to submit the release to OPAM repository ASAP.
